# Generated by Django 3.1.3 on 2020-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20201129_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-11-30'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-11-30'),
        ),
    ]
